spring:
  datasource:
    url: jdbc:postgresql:telemedicine_project
    username: postgres
    password: Miller_dev12
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
